# Generated by Django 3.2.12 on 2022-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMCConfigurations',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('template_id', models.BigIntegerField()),
                ('config', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'dmc_configurations',
                'verbose_name_plural': 'dmc_configurations',
                'db_table': 'dmc_configurations',
            },
        ),
    ]
