# Generated by Django 3.2.12 on 2023-01-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_mapping_console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmcconfigurations',
            old_name='config',
            new_name='data',
        ),
    ]
